[package]
name = "ru_psw_mng"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.29.0"
ring = "0.17.5"
data-encoding = "2.4.0"
clap = "4.4.8"